name=input("enter your name ")
age=input("enter your age ")
place=input("enter your place")
f1=input("enter your father name")
weight=input("enter your weight ")
height=input("enter your height ")
study=input("enter your class your studing ")
print("   ")
print(f"my name is {name} and i am {age} years old   and my place is {place} and my father name is {f1}  and i amd studing in {study} and i have {weight} weight and also {height} height")
