name =input("what is your name  ")
place =input("where is your place  ")
study=input("were is you studiying  ")
father=input("what is your father name  ")
mother=input("what is your mother name  ")
print("           ")
print("my name is " + name )
print("my place is " + place)
print("i am studing in " + study)
print("my father name is " + father)
print("my mother name is " + mother)
