name=input("Entre your name  ")
place=input("Enter your place  ")
number=input("Enter your phone number ")
father=input("Enter your father name ")
mother=input("Enter your mother name ")
print("My name is " + name)
print("my place is " + place)
print("my phone number is" + number)
print("My father name is  " + father)
print("My mother name is " + mother)
