from turtle import Turtle,Screen
s1=Screen()
asl=Turtle()
asl.shape("turtle")

asl.hideturtle()
asl.penup()
asl.goto(+200,+100)
asl.pendown()
asl.color("black","red")
asl.begin_fill()
asl.forward(100)
asl.left(90)
asl.forward(100)
asl.left(90)
asl.forward(100)
asl.left(90)
asl.forward(100)
asl.end_fill()

asl.penup()
asl.goto(+200,-100)
asl.pendown()
asl.color("black","blue")
asl.begin_fill()
asl.forward(50)    
asl.left(45)    
asl.forward(50)
asl.left(45)
asl.forward(50)
asl.left(45)
asl.forward(50)
asl.left(45)
asl.forward(50)
asl.left(45)
asl.forward(50)
asl.left(45)
asl.forward(50)
asl.left(45)
asl.forward(50)
asl.left(45)
asl.forward(50)
asl.end_fill()

asl.penup()
asl.goto(-200,-200)
asl.pendown()
asl.color("black","green")
asl.left(90)
asl.begin_fill()
asl.forward(120) 
asl.left(120)
asl.forward(120) 
asl.left(120)
asl.forward(120) 
asl.end_fill()


asl.penup()
asl.goto(-200,+180)
asl.pendown()
asl.color("black","yellow")
asl.begin_fill()
asl.circle(60)
asl.end_fill()

s1.mainloop()